sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t kamelbouzid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kamelbouzid/react-test npm test -- --coverage


after_success:
  - docker build -t kamelb/multi-client ./client
  - docker build -t kamelb/multi-nginx ./nginx
  - docker build -t kamelb/multi-server ./server
  - docker build -t kamelb/multi-worker ./worker

#Log in to Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push them to docker hub

  - docker push kamelb/multi-client
  - docker push kamelb/multi-nginx
  - docker push kamelb/multi-server
  - docker push kamelb/multi-worker